#!/bin/sh
# Warden install script

DEFAULT="/usr/local"

if [ -z "$1" ] ; then
        LB="${DEFAULT}"
else
        LB="${1}"
fi

PROGDIR="${LB}/share/overmind"

mkdir -p ${PROGDIR} >/dev/null 2>/dev/null

DIR=`dirname $0`
cd ${DIR}

cp overmind.sh ${LB}/bin/overmind
chmod 755 ${LB}/bin/overmind

cp share/* ${PROGDIR}/
chmod 755 ${PROGDIR}/overmind-lib.sh

exit 0
